// <auto-generated />
using LLMS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LLMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220306130435_sqlLiteDb")]
    partial class sqlLiteDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("LLMS.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Approval")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Semester")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestorUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("LLMS.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "fd262146-b53c-47b3-afc2-6484643c68d1",
                            UserEmail = "admin.test@kitm.lt",
                            UserName = "Admin Akademija IT test",
                            UserRole = "Coordinator"
                        });
                });

            modelBuilder.Entity("LLMS.Models.Request", b =>
                {
                    b.HasOne("LLMS.Models.User", "Requestor")
                        .WithMany("UserRequests")
                        .HasForeignKey("RequestorUserId");

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("LLMS.Models.User", b =>
                {
                    b.Navigation("UserRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
